FROM ubuntu:16.04

# setup nginx and put its daemon off
run apt-get update && apt-get install -y nginx \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
    && echo "daemon off;" >> /etc/nginx/nginx.conf

# this is our default conf file for nginx
ADD default /etc/nginx/sites-available/default

# copy html website into this container
COPY application/html/* /var/www/html/

# make container's port 80 (nginx default http port) accessible to the outside
EXPOSE 80

# run nginx
CMD [ "nginx" ]
